/* eslint-env node */

/**
 * Abyss — Extended spot configuration for dive visibility prediction.
 *
 * Adds dive-specific metadata (depth, sediment type, bathymetry, baseline vis)
 * on top of the existing Kaicast spot fields.
 */

const ABYSS_SPOTS = [
  {
    // --- existing Kaicast fields ---
    id: 'sharks-cove',
    name: "Shark's Cove",
    lat: 21.6417,
    lon: -158.0617,
    tz: 'Pacific/Honolulu',
    coast: 'north',
    buoyStation: '51201',
    tideStation: '1612668',
    runoffSensitivity: 'low',
    nearStreamMouth: false,
    nearDrainage: false,
    maxCleanSwellFt: 3,
    hardNoGoSwellFt: 6,

    // --- Abyss fields ---
    siteType: 'reef',
    maxDepthM: 15,
    typicalDiveDepthM: 8,
    sedimentType: 'coral_rubble',
    sedimentSensitivity: 'medium',
    bathymetryProfileM: [
      { distFromShoreM: 0, depthM: 1 },
      { distFromShoreM: 50, depthM: 5 },
      { distFromShoreM: 100, depthM: 10 },
      { distFromShoreM: 150, depthM: 15 },
    ],
    groundwaterInfluence: false,
    typicalBaselineVisM: 18,
    noaaTideStation: '1612668',
  },
  {
    id: 'three-tables',
    name: 'Three Tables',
    lat: 21.6367,
    lon: -158.0633,
    tz: 'Pacific/Honolulu',
    coast: 'north',
    buoyStation: '51201',
    tideStation: '1612668',
    runoffSensitivity: 'low',
    nearStreamMouth: false,
    nearDrainage: false,
    maxCleanSwellFt: 3,
    hardNoGoSwellFt: 6,

    siteType: 'reef',
    maxDepthM: 12,
    typicalDiveDepthM: 6,
    sedimentType: 'coral_rubble',
    sedimentSensitivity: 'medium',
    bathymetryProfileM: [
      { distFromShoreM: 0, depthM: 1 },
      { distFromShoreM: 40, depthM: 4 },
      { distFromShoreM: 80, depthM: 8 },
      { distFromShoreM: 120, depthM: 12 },
    ],
    groundwaterInfluence: false,
    typicalBaselineVisM: 15,
    noaaTideStation: '1612668',
  },
  {
    id: 'mokuleia',
    name: 'Mokuleia',
    lat: 21.5783,
    lon: -158.1553,
    tz: 'Pacific/Honolulu',
    coast: 'north',
    buoyStation: '51201',
    tideStation: '1612668',
    runoffSensitivity: 'medium',
    nearStreamMouth: false,
    nearDrainage: false,
    maxCleanSwellFt: 2,
    hardNoGoSwellFt: 5,

    siteType: 'shore',
    maxDepthM: 10,
    typicalDiveDepthM: 5,
    sedimentType: 'sand',
    sedimentSensitivity: 'high',
    bathymetryProfileM: [
      { distFromShoreM: 0, depthM: 1 },
      { distFromShoreM: 50, depthM: 3 },
      { distFromShoreM: 100, depthM: 6 },
      { distFromShoreM: 200, depthM: 10 },
    ],
    groundwaterInfluence: false,
    typicalBaselineVisM: 10,
    noaaTideStation: '1612668',
  },
  {
    id: 'makua',
    name: 'Makua Beach',
    lat: 21.527379,
    lon: -158.229536,
    tz: 'Pacific/Honolulu',
    coast: 'west',
    buoyStation: '51202',
    tideStation: '1612482',
    runoffSensitivity: 'high',
    nearStreamMouth: true,
    nearDrainage: false,
    maxCleanSwellFt: 3,
    hardNoGoSwellFt: 6,

    siteType: 'reef',
    maxDepthM: 20,
    typicalDiveDepthM: 12,
    sedimentType: 'sand',
    sedimentSensitivity: 'high',
    bathymetryProfileM: [
      { distFromShoreM: 0, depthM: 1 },
      { distFromShoreM: 50, depthM: 5 },
      { distFromShoreM: 100, depthM: 10 },
      { distFromShoreM: 200, depthM: 20 },
    ],
    groundwaterInfluence: false,
    typicalBaselineVisM: 12,
    noaaTideStation: '1612482',
  },
  {
    id: 'hanauma-bay',
    name: 'Hanauma Bay',
    lat: 21.2694,
    lon: -157.6939,
    tz: 'Pacific/Honolulu',
    coast: 'south',
    buoyStation: '51202',
    tideStation: '1612301',
    runoffSensitivity: 'low',
    nearStreamMouth: false,
    nearDrainage: false,
    maxCleanSwellFt: 4,
    hardNoGoSwellFt: 7,

    siteType: 'reef',
    maxDepthM: 10,
    typicalDiveDepthM: 5,
    sedimentType: 'reef',
    sedimentSensitivity: 'low',
    bathymetryProfileM: [
      { distFromShoreM: 0, depthM: 1 },
      { distFromShoreM: 30, depthM: 3 },
      { distFromShoreM: 60, depthM: 5 },
      { distFromShoreM: 100, depthM: 10 },
    ],
    groundwaterInfluence: false,
    typicalBaselineVisM: 20,
    noaaTideStation: '1612301',
  },
];

module.exports = { ABYSS_SPOTS };
