// CharterBriefScreen — PUBLIC read-only briefing share page.
//
// This route is the only charter URL that doesn't require auth. The
// share token in `?t=…` must match the trip's briefingShareToken
// before any content renders. Anyone with the link sees the briefing;
// nobody else can iterate / guess their way in because the token is
// long enough that brute-forcing isn't viable and the rules deny
// reads of charter_accounts/{orgId}/trips/{tripId} without it.
//
// Layout is intentionally print-friendly — captains text or WhatsApp
// this URL to their crew, who often print or screenshot it before
// boarding. No nav, no shell — standalone page.

import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { colors, fonts, radius } from '../tokens';
import type { RouteParams } from '../router';

export function CharterBriefScreen({ params }: { params?: RouteParams }) {
  const tripId = params?.tripId ?? null;
  const token = params?.briefToken ?? null;
  const ready = !!tripId && !!token;

  return (
    <View style={styles.page}>
      <View style={styles.printable}>
        <View style={styles.header}>
          <Text style={styles.kicker}>CREW BRIEFING</Text>
          <Text style={styles.title}>KaiCast Charter</Text>
        </View>

        {!ready ? (
          <View style={styles.errCard}>
            <Text style={styles.errTitle}>This briefing link is incomplete.</Text>
            <Text style={styles.errBody}>
              A valid brief URL looks like{' '}
              <Text style={styles.mono}>/charter/brief/&lt;tripId&gt;?t=&lt;token&gt;</Text>. Ask
              the captain who sent you to resend the link.
            </Text>
          </View>
        ) : (
          <View style={styles.scaffoldCard}>
            <Text style={styles.scaffoldKicker}>PHASE 6</Text>
            <Text style={styles.scaffoldTitle}>Read-only briefing renders here.</Text>
            <Text style={styles.scaffoldBody}>
              Trip date + departure time + ordered spot list + conditions at each spot at planned
              arrival time + per-leg crossing conditions + today's hazard strip + crew list (names
              and roles only — never certs or contact info) + float plan summary.
            </Text>
            <View style={styles.monoBlock}>
              <Text style={styles.scaffoldMono}>trip id: {tripId}</Text>
              <Text style={styles.scaffoldMono}>token:   {token.slice(0, 8)}…</Text>
            </View>
            <Text style={styles.scaffoldBody}>
              Print-friendly layout — captains pass this link to crew via text/WhatsApp and many
              crew screenshot or print before boarding. The page intentionally has no charter nav
              chrome.
            </Text>
          </View>
        )}

        <Text style={styles.footer}>
          Generated by KaiCast · live conditions valid as of last forecast update
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg, alignItems: 'center', padding: 24 },
  printable: {
    width: '100%',
    maxWidth: 760,
    backgroundColor: colors.surface0,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.hairline,
    padding: 36,
    gap: 24,
  },
  header: { gap: 6, borderBottomWidth: 1, borderBottomColor: colors.hairline, paddingBottom: 18 },
  kicker: {
    fontFamily: fonts.mono,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    color: colors.accent,
  },
  title: {
    fontFamily: fonts.display,
    fontSize: 28,
    fontWeight: '800',
    color: colors.text1,
    letterSpacing: -0.5,
  },
  errCard: {
    padding: 20, borderRadius: radius.md,
    backgroundColor: 'rgba(247,55,38,0.10)',
    borderWidth: 1, borderColor: '#F73726',
    gap: 8,
  },
  errTitle: { fontFamily: fonts.body, fontSize: 14, fontWeight: '700', color: '#F73726' },
  errBody: { fontFamily: fonts.body, fontSize: 13, color: colors.text2, lineHeight: 20 },
  mono: { fontFamily: fonts.mono, color: colors.text3, fontSize: 12 },
  monoBlock: { gap: 2 },
  scaffoldCard: { padding: 20, borderRadius: radius.md, backgroundColor: colors.surface1, borderWidth: 1, borderColor: colors.hairline, gap: 12 },
  scaffoldKicker: { fontFamily: fonts.mono, fontSize: 11, fontWeight: '700', letterSpacing: 1.5, color: colors.accent },
  scaffoldTitle: { fontFamily: fonts.display, fontSize: 18, fontWeight: '700', color: colors.text1 },
  scaffoldBody: { fontFamily: fonts.body, fontSize: 13, color: colors.text2, lineHeight: 20 },
  scaffoldMono: { fontFamily: fonts.mono, fontSize: 11, color: colors.text3, marginVertical: 2 },
  footer: {
    fontFamily: fonts.mono, fontSize: 10, color: colors.text4, textAlign: 'center',
    letterSpacing: 1, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.hairline,
  },
});
